#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

foamCleanPolyMesh -region fluidRegion
foamCleanPolyMesh -region neutroRegion
foamCleanPolyMesh -region thermoMechanicalRegion

rm -f *.dat *.foam
