#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

./Allrun.pre

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# The application name "GeN-Foam" is not compatible with
# the regex used by getApplication. It would have to be
# something like "genFoam" following OpenFOAM solver naming conventions.
#runApplication $(getApplication)

# Hardwire call to solver
GeN-Foam >> log.GeN-Foam 2>&1

postProcess -region fluidRegion -funcs '(mag(U) mag(UA))' >> log.postProcess.fluidRegion 2>&1
postProcess -region fluidRegion -func fluidRegionSingleGraphAA >> log.postProcess.fluidRegion 2>&1
postProcess -region fluidRegion -func fluidRegionSingleGraphBB >> log.postProcess.fluidRegion 2>&1

postProcess -region neutroRegion -func neutroRegionSingleGraphAA >> log.postProcess.neutroRegion 2>&1
postProcess -region neutroRegion -func neutroRegionSingleGraphBB >> log.postProcess.neutroRegion 2>&1
