#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

foamCleanPolyMesh -region fluidDynamics
foamCleanPolyMesh -region neutronTransport
foamCleanPolyMesh -region thermalMechanics

rm -f *.dat *.foam
