#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

./Allrun.pre

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication $(getApplication)

postProcess -region cavity -funcs '(mag(U) mag(UA))' >> log.postProcess.cavity 2>&1
postProcess -region cavity -func fluidDynamicsSingleGraphAA >> log.postProcess.cavity 2>&1
postProcess -region cavity -func fluidDynamicsSingleGraphBB >> log.postProcess.cavity 2>&1

# postProcess -region cavity/neutronTransport -func neutronTransportSingleGraphAA >> log.postProcess.cavity.neutronTransport 2>&1
# postProcess -region cavity/neutronTransport -func neutronTransportSingleGraphBB >> log.postProcess.cavity.neutronTransport 2>&1
