#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

./Allrun.pre

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication $(getApplication)

postProcess -region fluidDynamics -funcs '(mag(U) mag(UA))' >> log.postProcess.fluidDynamics 2>&1
postProcess -region fluidDynamics -func fluidDynamicsSingleGraphAA >> log.postProcess.fluidDynamics 2>&1
postProcess -region fluidDynamics -func fluidDynamicsSingleGraphBB >> log.postProcess.fluidDynamics 2>&1

postProcess -region neutronTransport -func neutronTransportSingleGraphAA >> log.postProcess.neutronTransport 2>&1
postProcess -region neutronTransport -func neutronTransportSingleGraphBB >> log.postProcess.neutronTransport 2>&1
